<a href="https://colab.research.google.com/github/19PA1A0528/7-3-2020/blob/master/Copy_of_Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Bias-To make the target function more easier and approximate, bias will simplify the assumptions made by the model.
variance-Variance is the amount that will estimate the target function will change for given different training data.

2.cross-validation is different from train-test split as cross-validation gives the oppurtunity to the model to train on multiple train-test split.

In [0]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression 
import matplotlib.pyplot as plt 

In [0]:
df=pd.read_csv("students_placement_data.csv")
df

Roll No Gender  ... registered_for_ Placement_Training  placement status
0          1      M  ...                                 NO        Not placed
1          2      F  ...                                yes            Placed
2          3      F  ...                                yes        Not placed
3          4      M  ...                                yes        Not placed
4          5      M  ...                                yes        Not placed
..       ...    ...  ...                                ...               ...
112      113      M  ...                                 NO        Not placed
113      114      M  ...                                 NO        Not placed
114      115      M  ...                                 NO        Not placed
115      116      M  ...                                 NO        Not placed
116      117      M  ...                                 NO        Not placed

[117 rows x 9 columns]

In [0]:
x=df[["SSC Percentage","inter_Diploma_percentage"]].values
y=df[["B.Tech_percentage"]].values

In [0]:
"x.shape

(117, 2)

In [0]:
y.shape

(117, 1)

In [0]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [0]:
model = LinearRegression()  
model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
model.intercept_

array([-8.93757155])

In [0]:
model.coef_

array([[0.13815068, 0.74767901]])

In [0]:
predicted_quality=model.predict(x_test)
predicted_quality.shape

(24, 1)

In [0]:
x_test.shape

(24, 2)

In [0]:
c=model.predict(x_test)
c

array([[59.48428235],
       [74.39237133],
       [47.70510932],
       [62.29059186],
       [62.07269608],
       [38.58534424],
       [63.65735244],
       [61.03401875],
       [64.21328587],
       [69.64778895],
       [69.47400295],
       [51.16069667],
       [72.0755656 ],
       [68.16310069],
       [64.41857474],
       [58.94306477],
       [61.57127722],
       [62.5781799 ],
       [71.03915168],
       [63.13088105],
       [66.63425342],
       [52.64568922],
       [69.41448084],
       [72.10369535]])

In [0]:
Actual_predicted=pd.DataFrame({"Actual": y_test.flatten(), "Predicted": predicted_quality.flatten()})

In [0]:
Actual_predicted.head()

Actual  Predicted
0   71.49  59.484282
1   81.10  74.392371
2   62.98  47.705109
3   68.70  62.290592
4   61.02  62.072696